# GENERATED by scripts/gen-homebrew-formula.mjs — do not edit by hand.
class Trove < Formula
  desc "The Trove command-line tool — knowledge base client + source/toolkit toolchain"
  homepage "https://ontrove.sh"
  version "2.0.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/hollyburnanalytics/trove-packages/releases/download/%40ontrove/cli%402.0.0/trove-darwin-arm64.tar.gz"
      sha256 "a7cebb4a8be9005110772c75ce34efa1858f9e8c21257791a9e27ead34bc773f"
    end
    on_intel do
      url "https://github.com/hollyburnanalytics/trove-packages/releases/download/%40ontrove/cli%402.0.0/trove-darwin-x64.tar.gz"
      sha256 "0a784f2e6017ac5f08fed7f53350e9e579b10ada37d361910b0954ce9d9acb4d"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/hollyburnanalytics/trove-packages/releases/download/%40ontrove/cli%402.0.0/trove-linux-arm64.tar.gz"
      sha256 "b9561699f60fe70a79e4c2a607fe735253335ea931d27d906143bbac3ddb06b4"
    end
    on_intel do
      url "https://github.com/hollyburnanalytics/trove-packages/releases/download/%40ontrove/cli%402.0.0/trove-linux-x64.tar.gz"
      sha256 "6b9e87f82ee6f922381fffc4a022e1db0a9202d69775f1d8eb68b2963ab62f35"
    end
  end

  def install
    bin.install Dir["trove-*"].first => "trove"
    prefix.install Dir["LICENSE", "THIRD-PARTY-LICENSES.txt"]
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/trove --version")
  end
end
