# GENERATED by scripts/gen-homebrew-formula.mjs — do not edit by hand.
class Trove < Formula
  desc "The Trove command-line tool — knowledge base client + source/toolkit toolchain"
  homepage "https://ontrove.sh"
  version "0.10.3"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/hollyburnanalytics/trove-packages/releases/download/%40ontrove/cli%400.10.3/trove-darwin-arm64.tar.gz"
      sha256 "e950916b1e2aaf7619240f495f0eb7e6db64b32ed1dfcc3bb881d2a7ba45dd34"
    end
    on_intel do
      url "https://github.com/hollyburnanalytics/trove-packages/releases/download/%40ontrove/cli%400.10.3/trove-darwin-x64.tar.gz"
      sha256 "71bc5404dcc81fe65b2ad6c4d9b0843fcdb06e46fec65aab425df479aa50ccef"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/hollyburnanalytics/trove-packages/releases/download/%40ontrove/cli%400.10.3/trove-linux-arm64.tar.gz"
      sha256 "0e23747fb0e7077ff0fdd41e18f134ad2c981c9d0375e35ded49ac1b8a1dac73"
    end
    on_intel do
      url "https://github.com/hollyburnanalytics/trove-packages/releases/download/%40ontrove/cli%400.10.3/trove-linux-x64.tar.gz"
      sha256 "8b241a13b9f4692b2e5405c656edad8ab9dcbd16713d828fbe75bd1e31ddbad5"
    end
  end

  def install
    bin.install Dir["trove-*"].first => "trove"
    prefix.install Dir["LICENSE", "THIRD-PARTY-LICENSES.txt"]
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/trove --version")
  end
end
